### PR TITLE
LDD Release 1.0.0.0 for IM Versions 1.20.0.0 and 1.21.0.0

### PR DESCRIPTION
**Pull request by jordanpadams**
LDD Release 1.0.0.0 for IM Versions 1.20.0.0 and 1.21.0.0 plus rebased with main

### CODE REVIEW

**Review by acraugh — CHANGES_REQUESTED** [review]
Jordan - the 1.19.0.0, version wasn't built. It looks like my changes to pds4_versions.txt were not merged. Was this deliberate, and if so why - since I made a point of noting that we need the 1.19.0.0 version?!  I'm going to go check that the other changes were merged.

**Review by acraugh — APPROVED** [review]

**Comment by acraugh** [comment]
I went ahead and added the 1.19.0.0 version, checked the successful build, and approved the changes. We're good to go on this one.  Thanks!

**Comment by jordanpadams** [comment]
@acraugh apologies for removing the 1.19.0.0 build. When I cleaned up the merge conflict it was just an oversight.

**Comment by acraugh** [comment]
No worries. I'll pick it up...

-Anne.

**Comment by acraugh** [comment]
@jordanpadams - I give up. I can't clear this block. I thought it might be an issue of a file in main having a later creation time than the one in release, but I rebuilt the release branch documents and the block persists. I don't know how to clear it, but the file that is causing the problem is a product, not a source. I also don't have a system set up where I can work from a git command line, and given changes in github validation requirements, that would be a non-trivial effort.

**Comment by jordanpadams** [comment]
@acraugh done. When a merge gets blocked like that in a pull request, it often happens when files get updated on 2 different branches at the same time, which in this case was `main` and `release/1.21.0.0_1.0.0.0_rebased`. In this case, the PDF was deleted on main, but updated here, so git didn't know what you wanted to do. Keep it or get rid of? 🤷

Sometimes you can resolve these conflicts in the GitHub interface, but sometimes it doesn't know how to show the diffs in the files (e.g. binary files in this case) so it just throws up it's hands. To resolve this, you just need to do the merge or rebase from main into your branch, resolve the conflict, and [push the updates to the branch](https://github.com/pds-data-dictionaries/ldd-sb/pull/9/commits/2eca099c2346caa306232b5ea3ca2d0f335f37d0). I tried rebase first, but it was painful (conflict after conflict), so I tried out the merge which was simple.

**Comment by acraugh** [comment]
OK, I did that, but not I cannot find the original pull request that was
blocked. Was it deleted, or did you do something in the background that I
just undid?

-Anne.

**Comment by jordanpadams** [comment]
@acraugh I just did this [merge commit here](https://github.com/pds-data-dictionaries/ldd-sb/pull/9/commits/2eca099c2346caa306232b5ea3ca2d0f335f37d0) on this branch to fix the problem.

**Pull request merged**
